Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 220

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false
