AllCops:
  TargetRubyVersion: 2.4

Layout/IndentHeredoc:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'swagger-diff.gemspec'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 250

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 10

# YAML.safe_load is not present in Ruby 2.0.
Security/YAMLLoad:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
