language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
before_install:
  - gem update --system
  - rvm @global do gem install bundler
branches:
  only:
    - master
